version: '3.8'

services:
  oracle-db:
    image: wnameless/oracle-xe-11g-r2:latest
    container_name: oracle-salon-belleza
    ports:
      - "1521:1521"
      - "8080:8080"
    environment:
      - ORACLE_ALLOW_REMOTE=true
    volumes:
      - oracle-data:/u01/app/oracle
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - salon-network
    restart: unless-stopped
    shm_size: 1g

volumes:
  oracle-data:

networks:
  salon-network:
    driver: bridge